---
- name: Create user using host scope variables
  hosts: 172.31.22.246
  tasks:
   - name: Create user
     user: 
       name: "{{a}}"
       password: "{{b}}"
       uid: "{{c}}"
       home: "{{d}}"
       shell: "{{e}}"
...

